// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW2VML2db2MSkqtpPlhDocc9UFgqf2ceY',
    appId: '1:806466887742:web:1cf881a58d3d668b9b316f',
    messagingSenderId: '806466887742',
    projectId: 'flutter-firebase-auth-d1874',
    authDomain: 'flutter-firebase-auth-d1874.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-d1874.appspot.com',
    measurementId: 'G-NG2JWCZTK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3E_TlagY7JV37_q12laclACvXG-MphH0',
    appId: '1:806466887742:android:e4b10d55e71a9b019b316f',
    messagingSenderId: '806466887742',
    projectId: 'flutter-firebase-auth-d1874',
    storageBucket: 'flutter-firebase-auth-d1874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zugTeUOzjB8-wALJP0UgXWXf1wRc6Zg',
    appId: '1:806466887742:ios:ede8ceb34422bbc39b316f',
    messagingSenderId: '806466887742',
    projectId: 'flutter-firebase-auth-d1874',
    storageBucket: 'flutter-firebase-auth-d1874.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );
}
